<a href="https://colab.research.google.com/github/22f1000003/MLP-CODE/blob/main/Pivot_table_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pivot Table**

A pivot table is a powerful data summarization tool used in data analysis. It allows you to reorganize and summarize tabular data in a flexible manner, providing a compact representation of complex data relationships. Pivot tables enable you to aggregate and visualize data based on one or more key variables, making it easier to identify patterns and trends within your dataset.

**Creating a Pivot Table in Pandas**

In [14]:
import pandas as pd
import numpy as np
# Create a DataFrame
data = {
    'Date': ['2022-01-01', '2022-01-01', '2022-01-02', '2022-01-02'],
    'Category': ['A', 'B', 'A', 'B'],
    'Value': [10, 20, 30, 40]
}
df = pd.DataFrame(data)

df

         Date Category  Value
0  2022-01-01        A     10
1  2022-01-01        B     20
2  2022-01-02        A     30
3  2022-01-02        B     40

In [16]:
table = df.pivot_table(values ='Value',index = 'Date',columns = 'Category')

In [17]:
table

Category       A     B
Date
2022-01-01  10.0  20.0
2022-01-02  30.0  40.0

In [19]:
data = {}
np.random.seed(2)
for i in [chr(x) for x in range(65,70)]:
  data['col'+i] = np.random.randint(1,100,10)
data['orderID'] = np.random.choice(['A', 'B', 'C'], 10)
data['product'] = np.random.choice(['Product1', 'Product2', 'Product3'], 10)
data['customer'] = np.random.choice(['Customer1', 'Customer2', 'Customer3', 'Customer4'], 10)
df2 = pd.DataFrame(data)
df2

   colA  colB  colC  colD  colE orderID   product   customer
0    41    96    68    69    51       B  Product2  Customer3
1    16    76     5    47     5       C  Product2  Customer1
2    73    86    43    71    91       B  Product2  Customer1
3    23    48    52    96    64       B  Product3  Customer3
4    44    64    39    84    80       A  Product1  Customer3
5    83    32    34    32    50       B  Product3  Customer1
6    76    91    59    67    40       C  Product3  Customer3
7     8    21    68    81    47       A  Product1  Customer1
8    35    38    70    53     9       C  Product1  Customer2
9    50    40    89    77    51       B  Product3  Customer3

In [22]:
table2 = df.pivot_table(values ='colA',index = 'orderID',
            columns = 'product',aggfunc = 'max',fill_value=0)
table2

product  Product1  Product2  Product3
orderID
A              44         0         0
B               0        73        83
C              35        16        76

In [25]:
table2 = df.pivot_table(values ='colA',index = ['orderID', 'customer'],
            columns = 'product',aggfunc = 'max',fill_value=0)
table2

product            Product1  Product2  Product3
orderID customer
A       Customer1         8         0         0
        Customer3        44         0         0
B       Customer1         0        73        83
        Customer3         0        41        50
C       Customer1         0        16         0
        Customer2        35         0         0
        Customer3         0         0        76